const APP_NAME = "MovieMove";
const API_KEY = "74d4610bb51158a29e22b4cc6766d91a";
const LANGUAGES = {
  en: {
    genresWord: "Genres",
    findWord: "Find",
    actorWord: "actor",
    movieWord: "movie",
    actorsWord: "Actors",
    moviesWord: "Movies",
    sortByWord: "Sort by",
    apiLang: "en-US",
    showMoreWord: "show more",
    searchResultWord: "Search result",
    inMoviesWord: "In movies",
    errorSentence: "Something goes wrong...",
    actorsError: "Error loading actors",
    moviesError: "Error loading movies",
    genresError: "Error loading genres",
    singleActorError: "Failed to load actor data",
    singleMovieError: "Failed to load movie data",
    loadingWord: "Loading...",
    notSuchPage: "Not such page",
    noRate: "NR",
    searchActors: "Search actors",
    searchMovies: "Search movies",
  },
  ru: {
    genresWord: "Жанры",
    findWord: "Найти",
    actorWord: "актера",
    movieWord: "фильм",
    actorsWord: "Актеры",
    moviesWord: "Фильмы",
    sortByWord: "Сортировать по",
    apiLang: "ru-RU",
    showMoreWord: "показать все",
    searchResultWord: "Результаты поиска по запросу",
    inMoviesWord: "В фильмах",
    errorSentence: "Что-то пошло не так...",
    actorsError: "Ошибка при загрузке актеров",
    moviesError: "Ошибка при загрузке фильмов",
    genresError: "Ошибка при загрузке жанров",
    singleActorError: "Не удалось загрузить данные об актере",
    singleMovieError: "Не удалось загрузить данные о фильме",
    loadingWord: "Загрузка...",
    notSuchPage: "Такой страницы нет",
    noRate: "БР",
    searchActors: "Поиск актеров",
    searchMovies: "Поиск фильмов",
  },
};

export { APP_NAME, API_KEY, LANGUAGES };
